routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CartController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProduitController;
use App\Http\Controllers\CategorieController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('home');
})->name('accueil');
Route::get("/",[HomeController::class,"index"])->name("accueil");
Route::get("/add-to-cart/{id}", [HomeController::class, "add_cart"])->name("home.add_cart");
Route::get("/cart", [CartController::class, "index"])->name("cart.index");
Route::get("/cart/detail/{id}", [CartController::class, "detail"])->name("cart.detail");
Route::get("/cart/remove/{id}", [CartController::class, "removeItem"])->name("cart.remove");
Route::get("/cart/clear", [CartController::class, "clear"])->name("cart.clear");
Route::get("/cart/submitOrder", [CartController::class, "submitOrder"])->name("cart.submitOrder");
Route::get("/cart/commander",[CartController::class,"commander"])->name("cart.commander");

Route::post("categories/searsh",[CategorieController::class,"searsh"])->name("categories.searsh");
Route::get("produits/searsh",[ProduitController::class,"searsh"])->name("produits.searsh");
Route::get("produits/null_quantite",[ProduitController::class,"null_quantite"])->name("produits.null_quantite");
Route::resource("categories",CategorieController::class);
Route::resource("produits",ProduitController::class);

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/categories/create.blade.php
 @extends('layouts.admin')
 @section('title','Ajouter une categorie')
 @section('content')
 <div class="contain">
    <h1>Creer une nouvelle categorie</h1>

    <form action="{{route('categories.store')}}" method="POST">
        @csrf
        <div>
        <label for="designation">Designation</label>
        <input type="text" name="designation" id="designation" value="{{old('designation')}}">
        </div>
         <div>
        <label for="description" class="labeltext">Description</label>
       <textarea name="description" class="text" id="description" cols="30" rows="10" >{{old('designation')}}</textarea>
          
        </div>
        <div>
            <input type="submit" value="Ajouter">
        </div>
    </form>
    </div>
    <div>
    
        @if($errors->any())
        <ul>
          @foreach($errors->all() as $er)
           <li>{{$er}}</li>
           
           @endforeach
        </ul>
         


        @endif
    </div>
@endsection

resources/views/categories/edit.blade.php
 @extends('layouts.admin')
 @section('title','Modifier une categorie')
 @section('content')

<div class="contain">
    <h1 class="edit-h1">Modifier la categorie num {{$cat->id}}</h1>
    <form action="{{route('categories.update',["category"=>$cat->id])}}" method="POST">
        @csrf
        @method('PUT')
        
            <div class="form-group">
              <label for="exampleFormControlFile1">Designation :</label>
              <input type="text" name="designation" class="form-control" id="exampleFormControlFile1" rows="3" value="{{old('designation',$cat->designation)}}">
            </div>
        <div class="form-group">
            <label for="exampleFormControlTextarea1">Description :</label>
            <textarea class="form-control" name="description" id="exampleFormControlTextarea1" rows="3">{{old('designation',$cat->description)}}</textarea>
          </div>
        <div>
            <input type="submit" value="Modifier">
        </div>
    </form>

    <div>
        @if($errors->any())
        <ul>
          @foreach($errors->all() as $er)
           <li>{{$er}}</li>
           
           @endforeach
        </ul>
         


        @endif
    </div>
</div>
@endsection

resources/views/categories/index.blade.php
 @extends('layouts.admin')
 @section('title','Gestion des categories')
 @section('content')
     
    <h1>Liste des categories</h1>
    <a href="{{route('categories.create')}}" class="a">Ajouter une nouvelle categorie</a>
    <div class="searsh">
      <form action="{{route('categories.searsh')}}" method="GET">
        @csrf
        <label for="searsh">searsh :</label>
        <input type="text" name="searsh" id="searsh">
        <input type="submit" value="searsh">
      </form>
    </div>
    <table id="tbl">
      <tr>
          <th>Id</th>
        <th>Designation</th>
        <th>Description</th>
        <th colspan="3">Actions</th>
      </tr>
      @foreach ($categories as $cat)
          <tr>
            <td>{{$cat->id}}</td>
            <td>{{$cat->designation}}</td>
            <td>{{$cat->description}}</td>
            <td><a href="{{route('categories.show',["category"=>$cat->id])}}">Details</a></td>
            <td><a href="{{route('categories.edit',["category"=>$cat->id])}}">Modifier</a></td>
            <td>
                <form action="{{route('categories.destroy',["category"=>$cat->id])}}" method="POST">
                    @method('DELETE')
                    @csrf
                    <input type="submit" value="Supprimer" onclick="return confirm('voulez-vous supprimer cette categorie?')">
                </form></td>
          </tr>

      @endforeach
    </table>
  
    <div class="style mx-auto">

      {{ $categories->links() }}

</div> 
 @endsection

resources/views/categories/show.blade.php
 @extends('layouts.admin')
 @section('title','Detail d \'une categorie')
 @section('content')
    <a href="{{route('categories.index')}}">Retourner vers la liste des categories</a>
    <h1>Detail de la categorie Num {{$cat->id}}</h1>
    <div>
        <p><strong>Designation:</strong> {{$cat->designation}}</p>
        <p><strong>Description:</strong> {{$cat->description}}</p>
    </div>
@endsection